dist: xenial
language: node_js

branches:
    except:
        - /^v[0-9]/

install:
    - npm ci

script:
    - npm run build

deploy:
    - provider: script
      script: npx semantic-release
      skip_cleanup: true
      on:
          tags: false
          branch: master
